  $("#footer").css("z-index",1);
  $("#footer").css("position","fixed");
  $("#footer").css("bottom","0px");
  $("#footer").css("width","100%");
  $("#footer").css("height",$("#f").height());
  $("#footer").css("overflow","hidden");
  $("#container").css("position","relative");
  $("#container").css("z-index",5);
  $("#container").css("margin-bottom",$("#f").height());
  $("#container").css("box-shadow","0px 1px 7px rgba(0, 0, 0, 0.8)");
