# Site settings
baseurl: "" # optional
url: "http://thezero.org"
name: TheZero
title: TheZero

# Author settings
author: TheZero
author_avatar: https://gravatar.com/avatar/0034b4b3f3aaeced2804f8f76aa94080
email: io@thezero.org
description: My Lair in the Webspace
keybase_username: thezero
twitter_username: Th3Zer0
github_username: TheZ3ro
bitbucket_username: Th3Zer0
github_repo: TheZ3ro/thez3ro.github.io
bitcoin: 1HLaDgzd6maSFJbSCBC4hToEpGA5BNdN29


# Build settings
permalink: pretty