# Site settings
baseurl: "" # optional
url: "http://thezero.org"
name: TheZero
title: TheZero

# Author settings
author: TheZero
description: My Lair in the Webspace

# Build settings
permalink: pretty

include: [".well-known"]
